version: '3'
services:
  iris:
    container_name: iris
    ports:
      - "52773:52773"
      - "51773:51773"
      - "2188:2188"
      volumes:
        - .:/ISC
        - ./key:/key
        - "/etc/localtime:/etc/localtime:ro"
      environment:
        - ISC_DATA_DIRECTORY=/ISC/dur
        - "TZ=America/Sao_Paulo"
    #command: --key /key/iris_prod.key docker update --restart unless-stopped iris