version: '3'
services:
  iris:
    image: intersystems/iris:2019.4.0.383.0
    container_name: iris
    ports:
      - "52773:52773"
      - "51773:51773"
      - "2188:2188"
    volumes:
      - .:/ISC
      - ./key:/key
      - /usr/lib/jvm/java-8-openjdk-amd64:/java_home
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ISC_DATA_DIRECTORY=/ISC/dur
    command: --key /key/iris.key
